encoding: utf-8
#safe:        false
#auto:        false
#server:      false
#server_port: 4000
#baseurl:     http://mattn.github.io
title:       Whisky & Woman

source:      .
destination: ./_site
plugins:     ./_plugins

exclude: ["scripts"]
